#!/usr/bin/python3

import os # to execute the programs
import sys # for argv

if(len(sys.argv) < 6):
    print("Usage: ./cache.py <replacement_policy> <block_size> <set_associativity> <number_of_sets> <input_trace>")
    print("    ->  <replacement_policy> can be:")
    print("          * lru")
    print("          * lfu")
    print("          * nru")
    print("          * plru")
    print("          * srrip")
    print("    ->  cache specifications can be any powers of 2")
    print("    ->  <input_trace> is the trace generated by using the Intel® pin tool (pinatrace)")

else:

    replacementPolicy = sys.argv[1]
    blockSize = sys.argv[2]
    setAssociativity = sys.argv[3]
    numberOfSets = sys.argv[4]
    inputTrace = sys.argv[5]

    if any(replacementPolicy in file for file in os.listdir("exe/")):
        os.system("g++ src/" + replacementPolicy + ".cpp src/cache.cpp -o exe/" + replacementPolicy)    
        os.system("gzip -dc " + inputTrace + " | exe/" + replacementPolicy + " " + numberOfSets + " " + blockSize + " " + setAssociativity)
    
    else:
        print("That replacement policy is not supported")